# Generated by Django 2.1.2 on 2018-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('cust_name', models.CharField(max_length=30)),
                ('voltage_R', models.DecimalField(decimal_places=2, max_digits=4)),
                ('voltage_Y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('voltage_B', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Ir', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Iy', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Ib', models.DecimalField(decimal_places=2, max_digits=3)),
                ('power', models.DecimalField(decimal_places=2, max_digits=4)),
                ('energy_consumption', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
