# Generated by Django 2.1.2 on 2018-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='Ib',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='Ir',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='Iy',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='power',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_B',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_R',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_Y',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
