# Generated by Django 2.1.2 on 2018-10-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0002_auto_20181029_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='Ib',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='Ir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='Iy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_B',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_R',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='voltage_Y',
            field=models.IntegerField(),
        ),
    ]
